version: '3'

services:
  user-service:
    image: aakashrawat1910/microservices-user-service:latest
    container_name: user-service
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  product-service:
    image: aakashrawat1910/microservices-product-service:latest
    container_name: product-service
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  order-service:
    image: aakashrawat1910/microservices-order-service:latest
    container_name: order-service
    ports:
      - "3002:3002"
    networks:
      - microservices-network

  gateway-service:
    image: aakashrawat1910/microservices-gateway-service:latest
    container_name: gateway-service
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - product-service
      - order-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge